# Generated by Django 3.0.4 on 2020-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_remove_batch_students'),
        ('students', '0002_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(to='batches.Batch'),
        ),
    ]
