# Generated by Django 3.0.4 on 2020-03-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='title',
        ),
    ]
