# Generated by Django 3.0.4 on 2020-03-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20200328_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='day',
        ),
        migrations.RemoveField(
            model_name='class',
            name='timing',
        ),
    ]
