# Generated by Django 3.0.4 on 2020-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20200328_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='timing',
            field=models.CharField(default='', max_length=20),
        ),
    ]
