# Generated by Django 3.0.4 on 2020-03-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('classes', '0010_auto_20200328_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Room'),
        ),
    ]
