# Generated by Django 3.0.4 on 2020-04-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_class_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
