# Generated by Django 3.0.4 on 2020-03-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.BooleanField(default=False)),
                ('sunday_timing', models.CharField(max_length=100)),
                ('monday', models.BooleanField(default=False)),
                ('monday_timing', models.CharField(max_length=100)),
                ('teacher', models.ManyToManyField(to='teachers.Teacher')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
