# Generated by Django 3.0.4 on 2020-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0002_student_courses'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
