# Generated by Django 3.0.4 on 2020-03-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20200328_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='courses',
        ),
    ]
