# Generated by Django 3.0.4 on 2020-04-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('batches', '0004_remove_batch_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
        ),
    ]
